# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f4edd6f425978112abb0f10c78daec08424be64b5fa0c09b96ec3dbacc715972975f2ce90b7c9d37c837081d34103d5f329e7d68c176c7d27161ceec1331da5

test:
  secret_key_base: 8ee6548ba84b81146351661f0c695416b754839b26ef096c6d0864fce831cfa838312f884eb15fe83fa7d47a7b402c86270adfd8ab36db9f62a335a9da8104d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
